Apply the ff:
- Remove boilerplate codes in gradle files
- Update kotlin and agp version
- Migrate from Kapt to KSP
- Use Room Plugin

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,41 +1,20 @@
 #!/bin/sh
-
-# shellcheck disable=SC2034
+error="🔴"
 passed="🟢"
-
-echo "Running ktlintCheck...."
-
-CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"
-
-if [ -z "$CHANGED_FILES" ]; then
-    echo "No Kotlin staged files."
-    exit 0
-fi;
-
-./gradlew --quiet ktlintCheck -PinternalKtlintGitFilter="$CHANGED_FILES"
-EXIT_CODE=$?
-if [ $EXIT_CODE -ne 0 ]; then
-  echo $OUTPUT
-  echo "*************************************************"
-  echo "*                 Ktlint failed                 *"
-  echo "* Please fix the above issues before committing *"
-  echo "*************************************************"
-  exit $EXIT_CODE
+z40=0000000000000000000000000000000000000000
+echo "Executing ktlintCheck..."
+./gradlew ktlintCheck
+if [ $? == 1 ]; then
+  echo "$error ktlint failed. Run ktlintFormat then try again."
+  exit 1
 else
-  echo "$passed Ktlint passed!"
+  echo "$passed ktlint passed!"
 fi
-
-# shellcheck disable=SC2028
-echo "Running detekt..."
+echo "Executing detekt..."
 ./gradlew detekt
-EXIT_CODE=$?
-if [ $EXIT_CODE -ne 0 ]; then
-  echo $OUTPUT
-  echo "***********************************************"
-  echo "                 Detekt failed                 "
-  echo " Please fix the above issues before committing "
-  echo "***********************************************"
-  exit $EXIT_CODE
+if [ $? == 1 ]; then
+  echo "$error detekt failed. Run detekt then try again."
+  exit 1
 else
   echo "$passed detekt passed!"
 fi
diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,46 +1,20 @@
 #!/bin/sh
-
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local sha1> <remote ref> <remote sha1>
-#
-# This sample shows how to prevent push of commits where the log message starts
-# with "WIP" (work in progress).
-
-remote="$1"
-url="$2"
-
 error="🔴"
 passed="🟢"
-
 z40=0000000000000000000000000000000000000000
-
-echo "Executing unit test..."
-./gradlew testDebugUnitTest
+echo "Executing ktlintCheck..."
+./gradlew ktlintCheck
 if [ $? == 1 ]; then
-  echo "$error Test failed."
+  echo "$error ktlint failed. Run ktlintFormat then try again."
   exit 1
 else
-  echo "$passed Test passed!"
+  echo "$passed ktlint passed!"
 fi
-
-#echo "Executing lint..."
-#./gradlew app-tindahangtapat:lintDevDebug
-#if [ $? == 1 ]; then
-#	echo "$error Lint failed."
-#	exit 1
-#else
-#	echo "$passed Lint passed!"
-#fi
+echo "Executing detekt..."
+./gradlew detekt
+if [ $? == 1 ]; then
+  echo "$error detekt failed. Run detekt then try again."
+  exit 1
+else
+  echo "$passed detekt passed!"
+fi
